<?php
echo '<!DOCTYPE html>';
echo '<html lang="pt-br">';
echo '';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<title>My Page</title>';
echo '<link rel="stylesheet" href="styleSara.css">';
echo '<link href="https://saraemilay.github.io/My-Page/style.css" rel="stylesheet"/>';
echo '<script scr="https://saraemilay.github.io/My-Page/script.html"></script>';
echo '';
echo '';
echo '</head>';
echo '';
echo '';
echo '<body style="background-color: black;">';
echo '<div id="fundo">';
echo '<header>';
echo '<div class="Caixa">';
echo '<h1 style="border: solid magenta 5px;">';
echo '';
echo '<ul>';
echo '<li>';
echo '<img src="eusara.jpg" ; style="border: solid 10px darkmagenta;">';
echo '</li>';
echo '';
echo '<li>';
echo '<p style="background-size: 6px auto contain; background-color: aliceblue;">Olá, Sou Sara.';
echo '</p>';
echo '';
echo '';
echo '<p style="font-size: 20px;color: aliceblue;">Sou estudante de Sistemas de Informação do CIn';
echo 'UFPE</p>';
echo '</li>';
echo '<li class="Int0">';
echo '<p> <a href="https://www.instagram.com/saraemilayyy/">';
echo '<img src="insta.png"></a>';
echo '<a href="https://www.linkedin.com/in/sara-araujo-pereira-045731216/">';
echo '<img src="link.png">';
echo '</a>';
echo '<a href="https://github.com/SaraEmilay">';
echo '<img src="github.png">';
echo '</a>';
echo '</p>';
echo '';
echo '</li>';
echo '</ul>';
echo '</h1>';
echo '';
echo '<div class="Int2">';
echo '<ul>';
echo '<li >';
echo '<p class="começo">';
echo 'Aos 17 anos sai da "caverna" da ignorância e desconhecimento, e, com isso, senti que';
echo 'precisava "tapar alguns buracos"';
echo 'deixados até esse período. Conheci uma renomada PHD em física Gabriela Bailas, ou "Bibi';
echo 'Bailas", a qual me mostrou a dimensão de';
echo 'conteúdo que ainda não conhecia no âmbito científico. Desde então, sou apaixonada pelo';
echo 'universo científico e tecnológico.';
echo '</p>';
echo '</li>';
echo '<li>';
echo '<img src="bibi.png">';
echo '</li>';
echo '';
echo '<li>';
echo '<p class="Eu">';
echo 'Com o tempo, o estudo intensivo se fez presente na minha rotina. Durante a época do vestibular decidi que teria que dar o meu melhor.';
echo 'Hoje vejo que todo o esforço foi compensado e estou muito ansiosa para o início das aulas no CIn da UFPE.';
echo '</p>';
echo '<li>';
echo '<img src="eu1.png">';
echo '';
echo '</li>';
echo '<li class="esp">';
echo '<p>Uma curiosidade sobre mim bem aleatória é que aprendi espanhol com 11 anos simplesmente assistindo novelas mexicanas no SBT.';
echo 'Hoje pretendo ficar fluente também no inglês e, futuramente, quem sabe, no francês. </p>';
echo '<img src=espanhol.gif width="250px" height="230px">';
echo '</li>';
echo '<li class="animais">';
echo '<p style="width: 20%;">';
echo 'Amo gatinhos e hamsters. Tenho uma gata chamada Nina e uma hamster falecida chamada Maria Antonieta.';
echo 'Sinto que nós humanos não merecemos os animais, eles são simplesmente uns anjinhos.';
echo '</p>';
echo '<p>';
echo '<img src="nina.jpg" width="200px" height="200px">';
echo '<img src="tonieta.jpg" width="200px" height="200px">';
echo '';
echo '</p>';
echo '';
echo '</li>';
echo '';
echo '</ul>';
echo '';
echo '</div>';
echo '';
echo '';
echo '</div>';
echo '';
echo '';
echo '</header>';
echo '';
echo '';
echo '</div>';
echo '<footer>';
echo '<p>';
echo 'Página da Sara ©';
echo '</p>';
echo '</footer>';
echo '</body>';
?>
